Resources:
  S3:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName : "mu.visitations"
  VisitationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "visitations"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
        -
          AttributeName: "unit"
          AttributeType: "S"
        -
          AttributeName: "area"
          AttributeType: "S"
        -
          AttributeName: "name"
          AttributeType: "S"
        -
          AttributeName: "masjid"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "unit"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "masjidIndex"
          KeySchema:
            -
              AttributeName: "masjid"
              KeyType: "HASH"
            -
              AttributeName: "unit"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes: 
              - "area" 
          ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3          
      LocalSecondaryIndexes:
        -
          IndexName: "nameIndex"
          KeySchema:
            -
              AttributeName: "unit"
              KeyType: "HASH"
            -
              AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        -
          IndexName: "areaIndex"
          KeySchema:
            -
              AttributeName: "unit"
              KeyType: "HASH"
              
            -
              AttributeName: "area"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 3
  VisitationsMetaDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "visitations_metadata"
      AttributeDefinitions:
        -
          AttributeName: "masjid"
          AttributeType: "S"
        -
          AttributeName: "unit"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "masjid"
          KeyType: "HASH"
        -
          AttributeName: "unit"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1